version: "3.8"

networks:
  backend:
    name: bookshop_network
    driver: bridge
services:
  bookshopdb:
    image: mongo
    hostname: bookshopdb
    container_name: bookshopdb
    restart: always
    ports:
      - 27017-27019:27017-27019
    networks:
      - backend
  productservice:
    image: productservice
    hostname: productservice
    container_name: bookshop_productservice
    restart: always
    build:
      context: ./product-ms
      dockerfile: Dockerfile
    ports:
      - 9001:9001
    networks:
      - backend
  accountservice:
    image: accountservice
    hostname: accountservice
    container_name: bookshop_accountservice
    build:
      context: ./account-ms
      dockerfile: Dockerfile
    ports:
      - 9002:9002
    networks:
      - backend
  shoppingcartservice:
    image: shoppingcartservice
    hostname: shoppingcartservice
    container_name: bookshop_shoppingcartservice
    build:
      context: ./shoppingcart-ms
      dockerfile: Dockerfile
    ports:
      - 9003:9003
    networks:
      - backend

