version: "3.8"

networks:
  backend:
    name: bookshop_network
    driver: bridge
services:
  bookshopdb:
    image: mongo:latest
    hostname: bookshopdb
    container_name: bookshopdb
    restart: always
    ports:
      - 27017-27019:27017-27019
    networks:
      - backend
  minioserver:
    image: bitnami/minio:latest
    hostname: minioserver
    container_name: minioserver
    restart: always
    environment: 
      MINIO_ACCESS_KEY: BookshopUser
      MINIO_SECRET_KEY: BookshopPass1234
      MINIO_DEFAULT_BUCKETS: bookshop:public
    ports:
      - 9000:9000
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  productservice:
    image: productservice
    hostname: productservice
    container_name: bookshop_productservice
    restart: always
    build:
      context: ./product-ms
      dockerfile: Dockerfile
    ports:
      - 9001:9001
    networks:
      - backend
    depends_on:
      minioserver:
        condition: service_healthy
  accountservice:
    image: accountservice
    hostname: accountservice
    container_name: bookshop_accountservice
    build:
      context: ./account-ms
      dockerfile: Dockerfile
    ports:
      - 9002:9002
    networks:
      - backend
  shoppingcartservice:
    image: shoppingcartservice
    hostname: shoppingcartservice
    container_name: bookshop_shoppingcartservice
    build:
      context: ./shoppingcart-ms
      dockerfile: Dockerfile
    ports:
      - 9003:9003
    networks:
      - backend
  localizationservice:
    image: localizationservice
    hostname: localizationservice
    container_name: bookshop_localizationservice
    build:
      context: ./localization-ms
      dockerfile: Dockerfile
    ports:
      - 9004:9004
    networks:
      - backend
  ui:
    image: bookshopui
    hostname: bookshopui
    container_name: bookshop_ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - backend

