kind: ReplicationController
apiVersion: v1
metadata:
  name: product-service
spec:
  replicas: 3
  selector:
    app: product-service
  template:
    spec:
      containers:
        - name: product-service
          image: hamzaak/bookshop-productms:1.0
          ports:
            - containerPort: 9001
              hostPort: 9001
    metadata:
      labels:
        app: product-service
        uses: mongo